<a href="https://colab.research.google.com/github/jeraldflowers/Inferencial-statistic-basic-tools/blob/main/Sampling_functions_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import random
import io

In [2]:
econdata = pd.read_csv('/content/econdata.csv')
econdata.head()

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
0,0,"19.424781053,-99.1327537959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1332...",307_130_11,Cuauhtémoc,B,Mercado,Pino Suárez
1,1,"19.4346139576,-99.1413808393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_008_01,Cuautémoc,A,Museo,Museo Nacional de Arquitectura Palacio de Bell...
2,2,"19.4340695945,-99.1306348409","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_002_12,Cuautémoc,A,Museo,Santa Teresa
3,3,"19.42489472,-99.12073393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_102_06,Venustiano Carranza,B,Hotel,Balbuena
4,4,"19.42358238,-99.12451093","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_115_12,Venustiano Carranza,B,Hotel,real

## Sampling Functions:

### 1. Simple Random Sampling

In [3]:
random_8 = econdata.sample(n=8)

random_8

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
79,79,"19.4299360348,-99.1445730919","{""type"": ""Polygon"", ""coordinates"": [[[-99.1450...",002_047_11,Cuauhtémoc,B,Mercado,San Juan
180,180,"19.4357633849,-99.1330511805","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_094_32,Cuautémoc,A,Hotel,"Catedral, S.A. DE C.V."
226,226,"19.4416748524,-99.1365878489","{""type"": ""Polygon"", ""coordinates"": [[[-99.1370...",004_052_01,Cuauhtémoc,B,Mercado,De Muebles
212,212,"19.42155871,-99.1426572917","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",001_095_08,Cuautémoc,B,Hotel,Orense
176,176,"19.4349517474,-99.1321782303","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_094_04,Cuautémoc,A,Museo,Fotografía
14,14,"19.4338441801,-99.1342731052","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_010_01,Cuautémoc,A,Hotel,Holiday inn Zocalo Ciudad de México
2,2,"19.4340695945,-99.1306348409","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_002_12,Cuautémoc,A,Museo,Santa Teresa
107,107,"19.4248237343,-99.1311696681","{""type"": ""Polygon"", ""coordinates"": [[[-99.1313...",307_128_04,Cuauhtémoc,B,Mercado,San Lucas

In [5]:
prop_25 = econdata.sample(frac=.25)

prop_25.head()

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
120,120,"19.438089976,-99.1374885065","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_086_24,Cuautémoc,A,Hotel,"Atlanta, S. DE R.L."
55,55,"19.4406333099,-99.1378562996","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_067_18,Cuautémoc,B,Hotel,Plaza Garibaldi
190,190,"19.43311885,-99.14512643","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_019_02,Cuautémoc,B,Hotel,Metropol
76,76,"19.4367072434,-99.1424407474","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_095_02,Cuautémoc,A,Museo,Franz Mayer
18,18,"19.4331161255,-99.1309438719","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_021_01,Cuautémoc,A,Museo,Museo Nacional de las Culturas

### 2. Systematic Sampling

In [6]:
def systematic_sampling(econdata, step):
  indexes = np.arange(0, len(econdata), step=step)
  systematic_sample = econdata.iloc[indexes]
  return systematic_sample

systematic_sample = systematic_sampling(econdata, 3)
systematic_sample

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
0,0,"19.424781053,-99.1327537959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1332...",307_130_11,Cuauhtémoc,B,Mercado,Pino Suárez
3,3,"19.42489472,-99.12073393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_102_06,Venustiano Carranza,B,Hotel,Balbuena
6,6,"19.43553422,-99.12324801","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",318_116_11,Venustiano Carranza,B,Hotel,San Antonio Tomatlan
9,9,"19.4407152937,-99.1498060057","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",012_146_22,Cuautémoc,B,Hotel,Detroit
12,12,"19.43990186,-99.14813347","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_079_16,Cuautémoc,B,Hotel,La Paz
...,...,...,...,...,...,...,...,...
216,216,"19.4247697438,-99.1249707246","{""type"": ""Polygon"", ""coordinates"": [[[-99.1250...",323_118_37,Venustiano Carranza,B,Mercado,Lamininas de La Merced
219,219,"19.4234096295,-99.1438351156","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_118_03,Cuautémoc,B,Hotel,Prado Floresta
222,222,"19.4397905042,-99.134628735","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_063_10,Cuautémoc,A,Hotel,Ladero
225,225,"19.43094655,-99.12455418","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_027_04,Venustiano Carranza,B,Hotel,Gran Veracruz
228,228,"19.4406567734,-99.1394531646","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_069_01,Cuautémoc,B,Museo,Tequila y Mescal

### 3. Stratified Sampling

In [10]:
econdata['estratificado'] = econdata ['delegacion'] + ", " + econdata['tipo']
(econdata['estratificado'].value_counts()/len(econdata)).sort_values(ascending=False)

Cuautémoc, Hotel                0.643478
Cuautémoc, Museo                0.156522
Venustiano Carranza, Hotel      0.078261
Cuauhtémoc, Mercado             0.073913
Venustiano Carranza, Mercado    0.047826
Name: estratificado, dtype: float64

In [9]:
def data_stratified(econdata, name_col_strat, values_strat, prop_strat, random_state=None):
  df_strat = pd.DataFrame(columns=econdata.columns)

  pos = -1
  for i in range(len(values_strat)):
    pos += 1
    if pos == len(values_strat) - 1:
      ratio_len = len(econdata) - len(df_strat)
    else:
      ratio_len = int(len(econdata) * prop_strat[i])


    df_filtered = econdata[econdata[name_col_strat] == values_strat[i]]
    df_temp = df_filtered.sample(replace=True, n=ratio_len, random_state=random_state)

    df_strat = pd.concat([df_strat, df_temp])

  return df_strat

In [11]:
values_strat = ['Cuautémoc, Hotel', 'Cuautémoc, Museo', 'Venustiano Carranza, Hotel' ,'Cuauhtémoc, Mercado' ,'Venustiano Carranza, Mercado']
prop_strat = [0.5, 0.2, 0.1, 0.1, 0.1]
df_strat = data_stratified(econdata, 'estratificado', values_strat, prop_strat, random_state = 42)
df_strat

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id,estratificado
164,164,"19.4388741511,-99.1413308257","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_113_03,Cuautémoc,B,Hotel,Dos Naciones,"Cuautémoc, Hotel"
142,142,"19.4263681354,-99.1327278126","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_127_14,Cuautémoc,A,Hotel,Ambar,"Cuautémoc, Hotel"
27,27,"19.4348360773,-99.1463945583","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_016_01,Cuautémoc,B,Hotel,Hilton Centro Histórico,"Cuautémoc, Hotel"
168,168,"19.4349726565,-99.147766133","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_014_23,Cuautémoc,B,Hotel,One Alameda,"Cuautémoc, Hotel"
113,113,"19.43374405,-99.13550135","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_012_13,Cuautémoc,A,Hotel,San Antonio,"Cuautémoc, Hotel"
...,...,...,...,...,...,...,...,...,...
128,128,"19.4270781084,-99.1210175514","{""type"": ""Polygon"", ""coordinates"": [[[-99.1214...",323_061_04(123),Venustiano Carranza,B,Mercado,San Ciprian,"Venustiano Carranza, Mercado"
37,37,"19.4271233834,-99.125111772","{""type"": ""Polygon"", ""coordinates"": [[[-99.1251...",323_065_01,Venustiano Carranza,B,Mercado,Dulceria,"Venustiano Carranza, Mercado"
163,163,"19.4265454033,-99.1224859032","{""type"": ""Polygon"", ""coordinates"": [[[-99.1231...",323_063_05,Venustiano Carranza,B,Mercado,NaN,"Venustiano Carranza, Mercado"
156,156,"19.4255480371,-99.1249308096","{""type"": ""Polygon"", ""coordinates"": [[[-99.1253...",323_138_04 (3),Venustiano Carranza,B,Mercado,Mariscos,"Venustiano Carranza, Mercado"
37,37,"19.4271233834,-99.125111772","{""type"": ""Polygon"", ""coordinates"": [[[-99.1251...",323_065_01,Venustiano Carranza,B,Mercado,Dulceria,"Venustiano Carranza, Mercado"